version: '3.8'

services:
  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: weatherwise_db
    environment:
      POSTGRES_USER: weatherwise
      POSTGRES_PASSWORD: weatherwise_password
      POSTGRES_DB: weatherwise
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U weatherwise -d weatherwise"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: weatherwise_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: